export const BACKGROUND_EMOJIS = [
  { emoji: '📚', top: '5%', left: '4%', size: '2.75rem', rotate: '-14deg' },
  { emoji: '📖', top: '12%', left: '88%', size: '2.25rem', rotate: '10deg' },
  { emoji: '✏️', top: '22%', left: '12%', size: '2rem', rotate: '18deg' },
  { emoji: '📝', top: '8%', left: '52%', size: '2.5rem', rotate: '-6deg' },
  { emoji: '🧮', top: '28%', left: '78%', size: '2.35rem', rotate: '-8deg' },
  { emoji: '🔬', top: '38%', left: '6%', size: '2.6rem', rotate: '12deg' },
  { emoji: '🧪', top: '45%', left: '92%', size: '2.4rem', rotate: '-16deg' },
  { emoji: '📐', top: '52%', left: '18%', size: '2.2rem', rotate: '22deg' },
  { emoji: '📊', top: '58%', left: '68%', size: '2.3rem', rotate: '-10deg' },
  { emoji: '🎓', top: '18%', left: '32%', size: '2.8rem', rotate: '6deg' },
  { emoji: '🏫', top: '65%', left: '42%', size: '2.5rem', rotate: '-12deg' },
  { emoji: '📓', top: '72%', left: '8%', size: '2.15rem', rotate: '14deg' },
  { emoji: '🔭', top: '35%', left: '48%', size: '2.45rem', rotate: '-20deg' },
  { emoji: '🌍', top: '48%', left: '85%', size: '2.55rem', rotate: '8deg' },
  { emoji: '🧬', top: '78%', left: '75%', size: '2.35rem', rotate: '-18deg' },
  { emoji: '🖊️', top: '85%', left: '22%', size: '2rem', rotate: '16deg' },
  { emoji: '📌', top: '32%', left: '62%', size: '1.85rem', rotate: '-24deg' },
  { emoji: '✂️', top: '62%', left: '28%', size: '2.1rem', rotate: '20deg' },
  { emoji: '🧠', top: '42%', left: '32%', size: '2.3rem', rotate: '-6deg' },
  { emoji: '🔢', top: '55%', left: '55%', size: '2.25rem', rotate: '10deg' },
  { emoji: '🖍️', top: '68%', left: '58%', size: '2rem', rotate: '-14deg' },
  { emoji: '📎', top: '15%', left: '68%', size: '1.9rem', rotate: '26deg' },
  { emoji: '⚗️', top: '75%', left: '48%', size: '2.4rem', rotate: '-8deg' },
  { emoji: '🗒️', top: '88%', left: '88%', size: '2.2rem', rotate: '12deg' },
];
